### ISSUE TITLE
Package for Void linux

### ISSUE THREAD

**Issue by cr6git** [yuune/clearine#1]
Hi @yuune ! :slightly_smiling_face:

Today I noticed your package `clearine-git` in AUR.

I proposed a package for Void linux, see my pull request: https://git.io/vxqQE

(as we don't use `systemd` , it was necessary to change the `reboot` / `poweroff` commands)

Regards.

**Comment by yuune** [comment]
Hi @cr6git 
I am happy to see that, I will update the README.md ASAP if that pr has been accepted (since I'm not carrying my notebooks at this time, maybe until the next monday).

Thanks.

**Comment by cr6git** [comment]
Accepted and merged in [ba89606](https://github.com/voidlinux/void-packages/commit/ba896063b9f2add04c6c583c70e00cfe56d61f88) :tada: 
````
xbps-install -S clearine
````
Regards.
